import fs from "node:fs";
import path from "node:path";
import * as prettier from "prettier";
import { z } from "zod";

import { CatalogEntrySchema, type CatalogEntry } from "@/lib/catalog/schema";
import type { Database } from "@/lib/database.types";

// Shared library of the catalog CLIs (`check.ts`, `migration.ts`, `schema.ts`, `draft.ts`): loads and validates
// `catalog/entries/*.json`, renders the snapshot migration, the published JSON Schema and entry files, and finds deleted
// entries.
// Importing it has no side effects; the CLIs do the I/O orchestration and exit codes.
//
// Snapshot migrations (`supabase/migrations/<UTC yyyymmddhhmmss>_screening_catalog_snapshot.sql`) are generated by
// `renderSnapshotSql()` and never edited. Each one upserts every entry, so the table mirrors the files. The drift check
// compares the rendered body with the newest snapshot byte for byte. Deleted entries are found through the slug
// manifest: every snapshot's header lists its slugs, one `-- catalog-slug: <slug>` line each, which is simpler and
// sturdier than parsing slugs back out of the VALUES. A snapshot without a manifest is reported, not skipped.

export const REPO_ROOT = path.resolve(import.meta.dirname, "../..");
export const ENTRIES_DIR = path.join(REPO_ROOT, "catalog", "entries");
export const JSON_SCHEMA_PATH = path.join(REPO_ROOT, "catalog", "entry.schema.json");
export const MIGRATIONS_DIR = path.join(REPO_ROOT, "supabase", "migrations");

const SNAPSHOT_FILE = /^(\d{14})_screening_catalog_snapshot\.sql$/;
const MIGRATION_FILE = /^(\d{14})_.+\.sql$/;
const MANIFEST_LINE = /^-- catalog-slug: (\S+)$/gm;

/** A repo-relative path for messages, e.g. `catalog/entries/foo.json`. */
export function displayPath(file: string): string {
  return path.relative(REPO_ROOT, file).split(path.sep).join("/");
}

// ---------------------------------------------------------------------------------------------------------------
// Entries
// ---------------------------------------------------------------------------------------------------------------

/** Formats a Zod issue path the way it reads in the JSON: `eligibility[0].requires[1].factor`. */
export function formatIssuePath(issuePath: readonly PropertyKey[]): string {
  let out = "";
  for (const key of issuePath) {
    if (typeof key === "number") out += `[${key}]`;
    else out += out ? `.${String(key)}` : String(key);
  }
  return out || "(entry)";
}

export type EntryResult = { ok: true; entry: CatalogEntry } | { ok: false; problems: string[] };

/** Validates one parsed entry file. `fileLabel` prefixes every message; `fileSlug` is the file name minus `.json`. */
export function validateEntry(fileLabel: string, fileSlug: string, raw: unknown): EntryResult {
  const parsed = CatalogEntrySchema.safeParse(raw);
  if (!parsed.success) {
    return {
      ok: false,
      problems: parsed.error.issues.map((issue) => `${fileLabel}: ${formatIssuePath(issue.path)}: ${issue.message}`),
    };
  }
  if (parsed.data.slug !== fileSlug) {
    return {
      ok: false,
      problems: [`${fileLabel}: slug: "${parsed.data.slug}" does not match the file name (expected "${fileSlug}")`],
    };
  }
  return { ok: true, entry: parsed.data };
}

export interface LoadResult {
  /** Valid entries, sorted by slug. */
  entries: CatalogEntry[];
  /** The slug of every `*.json` file, valid or not, sorted. */
  fileSlugs: string[];
  /** Per-file, per-field messages; empty when every file is valid. */
  problems: string[];
}

function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Reads and validates `catalog/entries/*.json`. Requires file name = `<slug>.json`; dotfiles are ignored. */
export function loadEntries(dir: string = ENTRIES_DIR): LoadResult {
  const entries: CatalogEntry[] = [];
  const fileSlugs: string[] = [];
  const problems: string[] = [];
  if (!fs.existsSync(dir)) return { entries, fileSlugs, problems: [`${displayPath(dir)}: directory is missing`] };

  const names = fs
    .readdirSync(dir)
    .filter((name) => !name.startsWith("."))
    .sort(compareStrings);
  for (const name of names) {
    const file = path.join(dir, name);
    const label = displayPath(file);
    if (!name.endsWith(".json")) {
      problems.push(`${label}: not a .json entry file; only <slug>.json files belong here`);
      continue;
    }
    const fileSlug = name.slice(0, -".json".length);
    fileSlugs.push(fileSlug);

    let raw: unknown;
    try {
      raw = JSON.parse(fs.readFileSync(file, "utf8"));
    } catch (error) {
      problems.push(`${label}: invalid JSON: ${error instanceof Error ? error.message : String(error)}`);
      continue;
    }
    const result = validateEntry(label, fileSlug, raw);
    if (result.ok) entries.push(result.entry);
    else problems.push(...result.problems);
  }

  // File names are unique within a directory and every valid slug equals its file name, so this only trips if the
  // loading rules above ever change.
  const seen = new Set<string>();
  for (const entry of entries) {
    if (seen.has(entry.slug)) problems.push(`catalog/entries: duplicate slug "${entry.slug}"`);
    seen.add(entry.slug);
  }

  entries.sort((a, b) => compareStrings(a.slug, b.slug));
  return { entries, fileSlugs, problems };
}

// ---------------------------------------------------------------------------------------------------------------
// Snapshot SQL
// ---------------------------------------------------------------------------------------------------------------

type CatalogRow = Database["public"]["Tables"]["screening_catalog"]["Row"];
type EntryColumn = keyof CatalogEntry;
type Equals<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
/** Compile-time guard: fails `astro check` when the entry schema and the table columns (`npm run db:types`) drift. */
export const ENTRY_MATCHES_TABLE: Equals<EntryColumn, Exclude<keyof CatalogRow, "created_at" | "updated_at">> = true;

/** Entry columns in schema (= table) order. */
export const ENTRY_COLUMNS = Object.keys(CatalogEntrySchema.shape) as EntryColumn[];
const JSONB_COLUMNS = new Set<EntryColumn>(["eligibility", "interval_overrides", "sources"]);

export const SNAPSHOT_HEADER = [
  "-- Screening catalog snapshot, generated by `npm run catalog:migration` from catalog/entries/*.json — do not edit.",
  "-- Upserts every entry, drafts included (RLS hides them). Rows are never deleted: retire an entry instead.",
  "-- `npm run catalog:check` reads the catalog-slug manifest below to catch deleted entries.",
];

/**
 * A standard SQL string literal. Single quotes are doubled; backslashes are literal because Postgres has
 * `standard_conforming_strings` on (the default since 9.1, and on in Supabase).
 */
function quote(text: string): string {
  if (text.includes("\0")) throw new Error("a NUL character cannot be stored in a Postgres text value");
  return `'${text.replaceAll("'", "''")}'`;
}

function sqlLiteral(column: EntryColumn, value: unknown): string {
  if (value === undefined || value === null) return "null";
  // Zod output keeps schema key order, so JSON.stringify is canonical for validated entries.
  if (JSONB_COLUMNS.has(column)) return `${quote(JSON.stringify(value))}::jsonb`;
  switch (typeof value) {
    case "string":
      return quote(value);
    case "boolean":
      return value ? "true" : "false";
    case "number":
      if (!Number.isInteger(value)) throw new Error(`${column}: expected an integer, got ${value}`);
      return String(value);
    default:
      throw new Error(`${column}: cannot render a ${typeof value} as SQL`);
  }
}

/**
 * The snapshot migration body: a slug manifest and one `insert … on conflict (slug) do update` over every entry.
 * Byte-deterministic: entries sorted by slug, columns and jsonb keys in schema order, no timestamps (the migration
 * file name carries the time). Throws on an empty list, which would be invalid SQL.
 */
export function renderSnapshotSql(entries: readonly CatalogEntry[]): string {
  if (entries.length === 0) throw new Error("renderSnapshotSql: no entries to render");
  const sorted = [...entries].sort((a, b) => compareStrings(a.slug, b.slug));
  const columns = [...ENTRY_COLUMNS, "updated_at"];

  const rows = sorted.map((entry) => {
    const values = ENTRY_COLUMNS.map((column) => sqlLiteral(column, entry[column]));
    values.push("now()");
    return `  (\n${values.map((v) => `    ${v}`).join(",\n")}\n  )`;
  });
  const updates = columns.filter((column) => column !== "slug").map((column) => `  ${column} = excluded.${column}`);

  return [
    ...SNAPSHOT_HEADER,
    ...sorted.map((entry) => `-- catalog-slug: ${entry.slug}`),
    "",
    "insert into public.screening_catalog (",
    columns.map((column) => `  ${column}`).join(",\n"),
    ") values",
    rows.join(",\n"),
    "on conflict (slug) do update set",
    `${updates.join(",\n")};`,
    "",
  ].join("\n");
}

/**
 * The slugs listed in a snapshot's `-- catalog-slug:` manifest, or null when it has none. Only the header (before
 * `insert into`) is read, so entry text that happens to contain a manifest-like line can't add a slug.
 */
export function parseSnapshotSlugs(sql: string): string[] | null {
  const header = sql.split(/^insert into /m)[0];
  const slugs = [...header.matchAll(MANIFEST_LINE)].map((match) => match[1]);
  return slugs.length > 0 ? slugs : null;
}

export interface Snapshot {
  file: string;
  body: string;
}

/** Every `*_screening_catalog_snapshot.sql` migration, oldest first. */
export function listSnapshots(dir: string = MIGRATIONS_DIR): Snapshot[] {
  return fs
    .readdirSync(dir)
    .filter((name) => SNAPSHOT_FILE.test(name))
    .sort(compareStrings)
    .map((name) => {
      const file = path.join(dir, name);
      return { file, body: fs.readFileSync(file, "utf8") };
    });
}

/** The newest migration version (`yyyymmddhhmmss`) of any kind, or null when there are none. */
export function newestMigrationVersion(dir: string = MIGRATIONS_DIR): string | null {
  const versions = fs
    .readdirSync(dir)
    .map((name) => MIGRATION_FILE.exec(name)?.[1])
    .filter((version) => version !== undefined)
    .sort(compareStrings);
  return versions.at(-1) ?? null;
}

/** Messages for every slug an earlier snapshot shipped that no entry file has any more (entries are retired, never deleted). */
export function findDeletedSlugs(fileSlugs: readonly string[], snapshots: readonly Snapshot[]): string[] {
  const present = new Set(fileSlugs);
  const problems: string[] = [];
  const reported = new Set<string>();
  for (const snapshot of snapshots) {
    const slugs = parseSnapshotSlugs(snapshot.body);
    if (slugs === null) {
      problems.push(`${displayPath(snapshot.file)}: no "-- catalog-slug:" manifest; snapshots must not be hand-edited`);
      continue;
    }
    for (const slug of slugs) {
      if (present.has(slug) || reported.has(slug)) continue;
      reported.add(slug);
      problems.push(
        `catalog/entries/${slug}.json: missing, but ${displayPath(snapshot.file)} shipped it; ` +
          `restore the file and set "status": "retired" instead of deleting it`,
      );
    }
  }
  return problems;
}

/** `<UTC yyyymmddhhmmss>_screening_catalog_snapshot.sql` for the given time. */
export function snapshotFileName(now: Date): string {
  const version = now
    .toISOString()
    .replace(/\.\d{3}Z$/, "")
    .replace(/[-:T]/g, "");
  return `${version}_screening_catalog_snapshot.sql`;
}

// ---------------------------------------------------------------------------------------------------------------
// Published JSON Schema
// ---------------------------------------------------------------------------------------------------------------

/**
 * `catalog/entry.schema.json` as it should be on disk: `z.toJSONSchema(CatalogEntrySchema)` formatted with the
 * repo's Prettier config, so the pre-commit `prettier --write` leaves it unchanged. Refinements are not part of it.
 */
export async function renderJsonSchema(): Promise<string> {
  return formatJson(z.toJSONSchema(CatalogEntrySchema), JSON_SCHEMA_PATH);
}

/** `catalog/entries/<slug>.json` for an entry, formatted like `renderJsonSchema()` so pre-commit Prettier keeps it. */
export async function renderEntryFile(entry: CatalogEntry): Promise<string> {
  return formatJson(entry, entryFilePath(entry.slug));
}

/** The entry file path for a slug. The slug must already be validated (the schema allows only `[a-z0-9-]`). */
export function entryFilePath(slug: string): string {
  return path.join(ENTRIES_DIR, `${slug}.json`);
}

async function formatJson(value: unknown, filepath: string): Promise<string> {
  const options = await prettier.resolveConfig(filepath);
  return prettier.format(JSON.stringify(value, null, 2), { ...options, filepath });
}
